engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
ratings:
  paths:
    - "lib/"
exclude_paths:
- "doc/"
- "tmp"